import type { Metadata } from 'next'
import { PageShell } from '@/components/ui/page-shell'
import { SUPPORT_EMAIL } from '@/content/links'
import { site } from '@/content/site'

export const metadata: Metadata = {
  title: 'Terms of service',
  description: 'The terms you agree to when you use ImprovTalk.',
}

/*
 * No source for this existed in the app repo — it is written from scratch
 * against what the app actually does (weekly conversation quotas, Apple/Google
 * managed subscriptions, AI-generated coaching). It has NOT been reviewed by a
 * lawyer; that review should happen before store submission.
 */
export default function TermsPage() {
  return (
    <PageShell
      title="Terms of service"
      updated="30 August 2026"
      intro="Plain terms for using ImprovTalk. By installing the app or using the service, you agree to them."
    >
      <h2>What ImprovTalk is</h2>
      <p>
        ImprovTalk is a practice tool. It simulates conversations and scores your delivery so you
        can rehearse. It is a training aid — not therapy, not medical or psychological treatment,
        and not professional advice of any kind. If you need help with anxiety or distress, please
        speak to a qualified professional.
      </p>

      <h2>Your account</h2>
      <p>
        You need an account to use the service. Keep your sign-in credentials secure — you are
        responsible for activity under your account. You must be at least 13 years old, and old
        enough to form a binding contract where you live.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the service to harass, deceive, defraud or manipulate another person.</li>
        <li>Record or upload another person&rsquo;s voice without their knowledge and consent.</li>
        <li>Attempt to extract, reverse-engineer or resell the underlying models, prompts or content.</li>
        <li>Circumvent usage limits, or access the service by automated means.</li>
        <li>Upload unlawful content, or anything you do not have the right to upload.</li>
      </ul>
      <p>
        The coaching is designed for respectful conversation. The AI characters can and do decline,
        set boundaries and end conversations, and the app will not coach you to push past someone
        saying no. We may suspend accounts that use the service to rehearse harassment.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Conversations, hints, scores and suggested lines are generated by AI models. They can be
        wrong, awkward, or unsuitable for your situation. Treat them as practice material and use
        your own judgement. Scores measure specific, stated properties of your speech — they are not
        a verdict on you as a person.
      </p>

      <h2>Subscriptions and billing</h2>
      <p>
        ImprovTalk is free to start, with a weekly limit on AI conversations. Paid tiers raise or
        remove that limit. Subscriptions bought on iPhone are billed by Apple through your App Store
        account and are governed by Apple&rsquo;s terms; subscriptions bought elsewhere are billed by
        our payment processor.
      </p>
      <p>
        Subscriptions renew automatically until cancelled. Cancel any time from your App Store
        account settings — cancelling stops the next renewal and you keep access until the end of
        the period you have paid for. Refunds for purchases made through Apple are handled by
        Apple under their policies.
      </p>

      <h2>Your content</h2>
      <p>
        Your recordings, transcripts and scores remain yours. You grant us the limited licence
        needed to process them to run the service — transcribing, scoring and showing them back to
        you. We do not sell your content, and we do not use it to train models. What we store and
        for how long is set out in the <a href="/privacy/">privacy policy</a>.
      </p>

      <h2>Availability</h2>
      <p>
        We aim to keep the service running but do not guarantee uninterrupted availability. Features
        may change or be withdrawn. The service depends on third-party AI providers, and their
        outages will affect it.
      </p>

      <h2>Liability</h2>
      <p>
        The service is provided &ldquo;as is&rdquo;, without warranties of any kind to the extent
        permitted by law. We are not liable for indirect or consequential loss, or for outcomes of
        conversations you have in the real world. Nothing here limits liability that cannot lawfully
        be limited. If you are a consumer, you keep all statutory rights that apply where you live.
      </p>

      <h2>Ending it</h2>
      <p>
        You can stop using the service and delete your account at any time from Settings. We may
        suspend or terminate an account that breaches these terms.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms. Material changes will be signalled in the app or by email before
        they take effect. Continuing to use the service after that means you accept the new terms.
      </p>

      <h2>Contact</h2>
      <p>
        {site.legalEntity} — <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>
      </p>
    </PageShell>
  )
}
