/* Generated by scripts/gen-clip.mjs — do not edit; re-run npm run gen:clip. */
export const CLIP = {
  src: '/app/practice-clip.mp4',
  poster: '/app/practice-clip-poster.webp',
  width: 720,
  height: 1560,
  duration: 18.8,
  alt: "A Practice session in the ImprovTalk app: the persona’s portrait in a coffee shop, a hint on what to say next, the Hold-to-speak disc, and End & score.",
} as const

/** The score screen, a flat still from the Simulator; null when none was captured. */
export const SCORE_STILL = {
  src: '/app/score-still.webp',
  width: 720,
  height: 1561,
  alt: 'The score screen: Charisma Score, what worked, what to work on, and the voice and delivery bars.',
} as const
