/* Generated by scripts/crop-renders.mjs — do not edit; re-run npm run gen:renders. */
export type RenderName = 'intro' | 'home' | 'setup-blend' | 'score-disc' | 'tab-bar' | 'live-session' | 'live-session-phone' | 'score-screen' | 'score-screen-phone' | 'icon-strip' | 'setup-rows' | 'choice-list' | 'plan-max'

export type Render = {
  src: string
  srcSet: string
  width: number
  height: number
  alt: string
}

export const RENDERS: Record<RenderName, Render> = {
  'intro': {
    src: '/app/intro-1400.webp',
    srcSet: '/app/intro-700.webp 700w, /app/intro-1400.webp 1400w',
    width: 1400,
    height: 1662,
    alt: "The ImprovTalk intro screen: a couple talking on a beach behind the wordmark.",
  },
  'home': {
    src: '/app/home-1400.webp',
    srcSet: '/app/home-700.webp 700w, /app/home-1400.webp 1400w',
    width: 1400,
    height: 1662,
    alt: "The Home screen: streak, charisma and closed rate, then six destinations — Simulate, Practice, Learn, Solo Drills, Stats, History.",
  },
  'setup-blend': {
    src: '/app/setup-blend-1400.webp',
    srcSet: '/app/setup-blend-700.webp 700w, /app/setup-blend-1400.webp 1400w',
    width: 1400,
    height: 1404,
    alt: "The setup blend: streak, charisma and closed rate above four personality sliders — red, blue, yellow, green — each at 25%.",
  },
  'score-disc': {
    src: '/app/score-disc-1400.webp',
    srcSet: '/app/score-disc-700.webp 700w, /app/score-disc-1400.webp 1400w',
    width: 1400,
    height: 1404,
    alt: "A Charisma Score of 74 out of 100, up 6 on baseline, above the Hold-to-speak disc.",
  },
  'tab-bar': {
    src: '/app/tab-bar-1400.webp',
    srcSet: '/app/tab-bar-700.webp 700w, /app/tab-bar-1400.webp 1400w',
    width: 1400,
    height: 272,
    alt: "The app tab bar: Home, Practice, Learn, History.",
  },
  'live-session': {
    src: '/app/live-session-1400.webp',
    srcSet: '/app/live-session-700.webp 700w, /app/live-session-1400.webp 1400w',
    width: 1400,
    height: 1235,
    alt: "A live session in a coffee shop: the persona’s portrait, the Hold-to-speak disc, a hint, and End & score.",
  },
  'live-session-phone': {
    src: '/app/live-session-phone-1400.webp',
    srcSet: '/app/live-session-phone-700.webp 700w, /app/live-session-phone-1400.webp 739w',
    width: 739,
    height: 1631,
    alt: "A live session in a coffee shop on a phone: the persona’s portrait, the Hold-to-speak disc, a hint, and End & score.",
  },
  'score-screen': {
    src: '/app/score-screen-1400.webp',
    srcSet: '/app/score-screen-700.webp 700w, /app/score-screen-1400.webp 992w',
    width: 992,
    height: 1800,
    alt: "The score screen: Charisma Score 74, what worked, what to work on, and six voice and delivery bars.",
  },
  'score-screen-phone': {
    src: '/app/score-screen-phone-1400.webp',
    srcSet: '/app/score-screen-phone-700.webp 700w, /app/score-screen-phone-1400.webp 741w',
    width: 741,
    height: 1633,
    alt: "The score screen on a phone: Charisma Score 74, what worked, what to work on, and six voice and delivery bars.",
  },
  'icon-strip': {
    src: '/app/icon-strip-1400.webp',
    srcSet: '/app/icon-strip-700.webp 700w, /app/icon-strip-1400.webp 1400w',
    width: 1400,
    height: 236,
    alt: "The ImprovTalk app icon beside three other apps on an iPhone home screen.",
  },
  'setup-rows': {
    src: '/app/setup-rows-1400.webp',
    srcSet: '/app/setup-rows-700.webp 700w, /app/setup-rows-1400.webp 992w',
    width: 992,
    height: 1040,
    alt: "Setup rows: Language, Disposition, Mood, Guard, and a Jealous friends stepper.",
  },
  'choice-list': {
    src: '/app/choice-list-1400.webp',
    srcSet: '/app/choice-list-700.webp 700w, /app/choice-list-1400.webp 992w',
    width: 992,
    height: 1040,
    alt: "A disposition choice list: Surprise me, Open, Neutral (selected), Guarded, Cold.",
  },
  'plan-max': {
    src: '/app/plan-max-1400.webp',
    srcSet: '/app/plan-max-700.webp 700w, /app/plan-max-1400.webp 992w',
    width: 992,
    height: 1040,
    alt: "The Max plan card, marked Recommended, with three inclusions and a Choose Max button.",
  },
}
