/**
 * Bake the site's icon font: a SUBSET of Google's Material Symbols Rounded —
 * the same family, the same weight and the same trick as the app's
 * apps/mobile/scripts/bake-material-symbols.sh, so the site draws exactly the
 * glyphs the app draws.
 *
 * Google's CSS API serves a per-name subset when asked with `icon_names=`, and
 * serves woff2 to a Chrome user-agent. Two files: outlined (FILL 0) and filled
 * (FILL 1). Codepoints come from Google's own table, emitted to lib/icons.ts so
 * a name that is not in the subset fails at the type level, not silently in the
 * browser as a missing-glyph box.
 *
 * To add an icon: append its name to NAMES and re-run `npm run gen:icons`.
 */
import { writeFile, mkdir } from 'node:fs/promises'

const NAMES = [
  'add', 'arrow_back', 'arrow_forward', 'arrow_outward', 'arrow_upward', 'auto_awesome', 'bolt',
  'check', 'chevron_right', 'close', 'crown', 'description', 'download',
  'expand_more', 'history', 'home', 'lightbulb', 'local_fire_department', 'menu',
  'mic', 'monitoring', 'open_in_new', 'palette', 'pause', 'phone_iphone',
  'play_arrow', 'remove', 'schedule', 'star', 'stop_circle', 'visibility',
  'volume_off', 'volume_up', 'workspace_premium',
]
const sorted = [...new Set(NAMES)].sort()
const list = sorted.join(',')

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
const API = 'https://fonts.googleapis.com/css2'
const CODEPOINTS =
  'https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints'

async function bake(fill, out) {
  const css = await (
    await fetch(
      `${API}?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,${fill},0&icon_names=${list}&display=block`,
      { headers: { 'User-Agent': UA } },
    )
  ).text()
  const url = css.match(/https:\/\/fonts\.gstatic\.com[^)]+/)?.[0]
  if (!url) throw new Error(`no font url in CSS response:\n${css.slice(0, 400)}`)
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer())
  if (buf.subarray(0, 4).toString() !== 'wOF2') throw new Error(`${out}: not woff2`)
  await writeFile(out, buf)
  console.log(`✓ ${out} (${(buf.length / 1024).toFixed(1)} KB, ${sorted.length} glyphs)`)
}

await mkdir('public/fonts', { recursive: true })
await bake(0, 'public/fonts/MaterialSymbolsRounded-subset.woff2')
await bake(1, 'public/fonts/MaterialSymbolsRounded-subset-filled.woff2')

const table = Object.fromEntries(
  (await (await fetch(CODEPOINTS)).text())
    .trim()
    .split('\n')
    .map((l) => l.split(' ')),
)
const missing = sorted.filter((n) => !table[n])
if (missing.length) throw new Error(`no codepoint for: ${missing.join(', ')}`)

const ts = `/* Generated by scripts/bake-icons.mjs — do not edit; add a name there and re-run. */
export const ICONS = {
${sorted.map((n) => `  ${n}: 0x${table[n]},`).join('\n')}
} as const

export type IconName = keyof typeof ICONS
`
await writeFile('lib/icons.ts', ts)
console.log(`✓ lib/icons.ts (${sorted.length} names)`)
